---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgresrelay
  name: postgresrelay-query-log
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
