---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresrelay
  name: postgresrelay
  namespace: default
spec:
  ports:
  - name: data
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: postgresrelay
  sessionAffinity: None
  type: ClusterIP
